#!/usr/bin/env python
# Copyright 2009-2019, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import os
import sys

# Use local stem development version
stem_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'stem')
if os.path.exists(stem_path):
  print('using local dev stem version\n')
  sys.path.insert(0, stem_path)

import nyx
import nyx.curses

if __name__ == '__main__':
  if '--demo-glyphs' in sys.argv:
    nyx.curses.demo_glyphs()
  else:
    nyx.main()
